apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
  labels:
    app.kubernetes.io/created-by: lightspeed-operator
    app.kubernetes.io/instance: olsconfig-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: olsconfig
    app.kubernetes.io/part-of: lightspeed-operator
    model: gpt-oss-20b
    environment: gpt-oss-20b
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: credentials
        models:
          - name: default
        name: ramalama
        type: openai
        url: http://gpt-oss-20b-ramalama-service.ramalama.svc.cluster.local:8080/v1
  ols:
    conversationCache:
      postgres:
        credentialsSecret: lightspeed-postgres-secret
        dbName: postgres
        maxConnections: 2000
        sharedBuffers: 256MB
        user: postgres
      type: postgres
    defaultModel: default
    defaultProvider: ramalama
    deployment:
      console:
        replicas: 1
      replicas: 1
    introspectionEnabled: true
    logLevel: INFO
  olsDataCollector:
    logLevel: INFO
