apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramalama-qwen-3
  labels:
    app: ramalama-qwen-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramalama-qwen-3
  template:
    metadata:
      labels:
        app: ramalama-qwen-3
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      containers:
      - name: ramalama-qwen
        image: quay.io/kugupta/qwen3-4b-ramalama:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        command: ["/usr/bin/llama-server"]
        args:
        - '--port'
        - '8080'
        - '--model'
        - '/mnt/models/Qwen3-4B-Q4_K_M.gguf/Qwen3-4B-Q4_K_M.gguf'
        - '--no-warmup'
        - '--jinja'
        - '--log-colors'
        - '--alias'
        - 'qwen-model'
        - '--ctx-size'
        - '20048'
        - '--temp'
        - '0.6'
        - '--cache-reuse'
        - '256'
        - '-ngl'
        - '-1'
        - '--threads'
        - '14'
        - '--top-k'
        - '20'
        - '--top-p'
        - '0.95'
        - '--min-p'
        - '0'
        - '--host'
        - '0.0.0.0'
        ports:
        - containerPort: 8080